import type {Metadata} from "next";
import {Geist, Geist_Mono} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import AppSidebar from "@/components/AppSidebar";
import {ThemeProvider} from "@/components/providers/theme-provider";
import {SidebarProvider} from "@/components/ui/sidebar";
import {cookies} from "next/headers";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  const cookieStore = await cookies();
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true";

  return (
    <html lang="en" suppressHydrationWarning>
    <body className={`${geistSans.variable} ${geistMono.variable} antialiased flex`}>
    <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
      <SidebarProvider defaultOpen={defaultOpen}>
        <AppSidebar/>
        <div className="flex-1 flex flex-col min-h-screen">
          <Navbar/>
          <main className="flex-1 p-4">{children}</main>
        </div>
      </SidebarProvider>
    </ThemeProvider>
    </body>
    </html>
  );
}